---
sudo: required
dist: trusty
language: node_js
node_js:
  - 6
before_install:
- |
    echo "machine github.com login reactjs-bot password $GITHUB_TOKEN" >~/.netrc
    unset GITHUB_TOKEN
    if [ "$TEST_TYPE" != build_website ] && \
      ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
    sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq yarn
    yarn --version
install:
  - yarn install
    